FileVersion = 1
Dependencies = {corlib = "*", libbson-beef = "*"}

[Project]
Name = "libmongoc-beef"
DefaultNamespace = "libmongoc"

[Configs.Debug.Win64]
OtherLinkFlags = "$(LinkFlags) Advapi32.lib ws2_32.lib Bcrypt.lib secur32.lib crypt32.lib Dnsapi.lib"
BeefLibType = "Static"
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\mongoc_d.lib"]

[Configs.Release.Win64]
OtherLinkFlags = "$(LinkFlags) Advapi32.lib ws2_32.lib Bcrypt.lib secur32.lib crypt32.lib Dnsapi.lib"
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\mongoc.lib"]
